version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - $HOME/mongo:/data/db

  eureka-server:
    build: eureka-server
    image: eureka-server:1.0.0
    container_name: eureka-server
    ports:
      - 8085:8085


  config-server:
    build: config-server
    image: config-server:1.0.0
    container_name: config-server
    restart: always
    ports:
      - 8888:8888

  api-gateway:
    build: api-gateway
    image: api-gateway:1.0.0
    container_name: api-gateway
    restart: always
    depends_on:
      - eureka-server
      - user-management
    ports:
      - 8080:8080
    links:
      - user-management
      - eureka-server

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 8045:5762

  user-management:
    build: user-management
    image: user-management:1.0.0
    container_name: user-management
    restart: always
    depends_on:
      - mysql
      - rabbitmq
      - config-server
      - eureka-server
    links:
      - mysql
      - rabbitmq
      - config-server
      - eureka-server


